FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm i
COPY ./ ./
ARG REACT_APP_SERVER_URL
ENV REACT_APP_SERVER_URL=$REACT_APP_SERVER_URL
ARG REACT_APP_YOUTUBE_DATA_API_KEY
ENV REACT_APP_YOUTUBE_DATA_API_KEY=$REACT_APP_YOUTUBE_DATA_API_KEY
CMD ["npm", "run", "start"]
